# Travis CI
before_script:
  - chmod +x script/bootstrap
  - chmod +x script/branding
  - chmod +x script/cibuild
  - chmod +x script/console
  - chmod +x script/cucumber
  - chmod +x script/default-site
  - chmod +x script/fmt
  - chmod +x script/proof
  - chmod +x script/rubies
  - chmod +x script/rubyprof
  - chmod +x script/stackprof
  - chmod +x script/test
  - chmod +x script/travis
  - chmod +x script/vendor-mimes

bundler_args: --without benchmark:site:development

script: script/cibuild

cache: bundler

language: ruby

sudo: false

rvm:
  - &ruby1 2.3.1
  - &ruby2 2.3.0
  - &ruby3 2.2.5

matrix:
  include:
    - rvm: 2.3.0
      env: TEST_SUITE=fmt
    - rvm: jruby-9.0.5.0
      env: TEST_SUITE=test
    - rvm: 2.3.0
      env: TEST_SUITE=default-site

env:
  matrix:
    - TEST_SUITE=test
    - TEST_SUITE=cucumber

branches:
  only:
    - master
    - 3.2.1

notifications:
  email:
    recipients:
      - SuriyaaKudoIsc@users.noreply.github.com
