# Travis CI
before_script:
  - chmod +x script/bootstrap
  - chmod +x script/branding
  - chmod +x script/cibuild
  - chmod +x script/console
  - chmod +x script/cucumber
  - chmod +x script/default-site
  - chmod +x script/fmt
  - chmod +x script/proof
  - chmod +x script/rubies
  - chmod +x script/rubyprof
  - chmod +x script/stackprof
  - chmod +x script/test
  - chmod +x script/travis
  - chmod +x script/vendor-mimes
  - bundle exec danger
bundler_args: --without benchmark:site:development
script: script/cibuild
cache: bundler
language: ruby
sudo: false

rvm:
  - &ruby1 2.3.3
  - &ruby2 2.3.0
  - &ruby3 2.2.6
  - &jruby jruby-9.1.7.0

matrix:
  include:
    - rvm: *ruby1
      env: TEST_SUITE=fmt
    - rvm: *ruby1
      env: TEST_SUITE=default-site
  exclude:
    - rvm: *jruby
      env: TEST_SUITE=cucumber

env:
  matrix:
    - TEST_SUITE=test
    - TEST_SUITE=cucumber
branches:
  only:
    - master
    - themes
    - 3.4-stable*

notifications:
  slack:
    secure: YZjawNDiMMMVPCIH+Z00wBr39Qftdia1Uq+CaaPPe8xYRzDi9gOowvnmfkjDQE8PIuHMVtuAF6L3yO8gHrCVnf3aKkj/frYNOgLmtkTr3xSbP/OvmWalS9Y4R/LpGIfKaUG/GE5hW6ZULbiB2ou5yOloWfeSBze5f1JWjyJrHao=
  email:
    recipients:
      - SuriyaaKudoIsc@users.noreply.github.com

addons:
  code_climate:
    repo_token:
      secure: "AABZoezqxFU4fGX+nQ/I1tKYojofvOWDq3Jw7wcFSw8Uuef29uYnk2YLZcuf2mp6b0YyE8igb9Cyymeo/gEWXaGdthSdazmgD5bQSeVsRYfCdY4NxAr6vCRd5S0QWKwp9jc5Ez2NOfgmwlHQWKCtmx/WlLGEAieycEQYt63K+20="
# regular test configuration
after_success:
  - bundle exec codeclimate-test-reporter
