# AppVeyor CI
version: "{build}"

clone_depth: 10

branches:
  only:
    - master
    #- themes

build: off

install:
  - SET PATH=C:\Ruby%RUBY_FOLDER_VER%\bin;%PATH%
  - bundle install --retry 5 --jobs=%NUMBER_OF_PROCESSORS% --clean --path vendor\bundle

environment:
  BUNDLE_WITHOUT: "benchmark:site:development"
  matrix:
    - RUBY_FOLDER_VER: "23"
      TEST_SUITE: "test"
    - RUBY_FOLDER_VER: "23"
      TEST_SUITE: "cucumber"
    - RUBY_FOLDER_VER: "23"
      TEST_SUITE: "fmt"
    - RUBY_FOLDER_VER: "23"
      TEST_SUITE: "default-site"
    - RUBY_FOLDER_VER: "23-x64"
      TEST_SUITE: "test"
    - RUBY_FOLDER_VER: "22"
      TEST_SUITE: "test"
# DISABLED:
#    - RUBY_FOLDER_VER: "21"
#      TEST_SUITE: "test"

test_script:
  - ruby --version
  - gem --version
  - bundler --version
  - bash ./script/cibuild

cache:
  # If one of the files after the right arrow changes, cache will be skipped
  - 'vendor\bundle -> appveyor.yml,Gemfile,bunto.gemspec'
