markdown: kramdown
highlighter: rouge

#gauges_id: 
google_analytics_id: UA-88019666-1
#google_site_verification: 

repository: https://github.com/bunto/bunto
help_url: https://github.com/bunto/bunto-help

#timezone: America/Los_Angeles

defaults:
  -
    scope:
      path: "_docs"
      type: "docs"
    values:
      layout: "docs"
  -
    scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "news_item"


collections:
  docs:
    permalink: /:collection/:path/
    output: true
  posts:
    permalink: /news/:year/:month/:day/:title/
    output: true

name: Bunto • Simple, blog-aware, static sites
description: Transform your plain text into static websites and blogs
url: https://buntowaf.tk

twitter:
  username: buntowaf

logo: /img/logo-2x.png

plugins_dir:
  - jekyll-avatar
  - jekyll-feed
  - jekyll-mentions
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap
  - jemoji

exclude:
  - .gitignore
  - README.md
